# Generated by Django 3.2.8 on 2022-06-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20220606_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
