# Generated by Django 3.2.8 on 2022-06-12 17:12

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=sqlalchemy.sql.expression.true, upload_to='user/profile/images/'),
        ),
    ]
