# Generated by Django 3.2.8 on 2022-06-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='user/profile/images/profile.png', null=True, upload_to='user/profile/images/'),
        ),
    ]
