# Generated by Django 3.2.8 on 2022-06-06 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0003_alter_user_last_seen'),
        ('Chat', '0001_initial'),
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Room.room'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.user'),
        ),
    ]
