# Generated by Django 3.2.8 on 2022-06-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image'), ('audio', 'audio'), ('document', 'document'), ('video', 'video'), ('voice_note', 'voice_note'), ('sticker', 'sticker')], default='text', max_length=255),
        ),
    ]
