# Generated by Django 3.2 on 2022-07-29 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_alter_user_profile'),
        ('Chat', '0003_message_attachment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='Account.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='Account.user'),
        ),
    ]
