# Generated by Django 3.2 on 2022-07-29 23:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0008_alter_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEETING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(default=uuid.UUID('a9e27398-4d18-4771-939f-8f346de75dd8'), max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, default=(('live', 'live'), ('end', 'end'), ('upcoming', 'upcoming')), max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PARTICIPANT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieved', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='Meeting.meeting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.user')),
            ],
        ),
    ]
