# Generated by Django 3.2 on 2022-07-29 23:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default=uuid.UUID('2213da11-18ea-4add-8d77-ecca4b5aa547'), max_length=255, unique=True),
        ),
    ]
