# Generated by Django 3.2 on 2022-07-30 00:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0003_auto_20220730_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
